version: '3.8'

services:
  mathew_db:
    image: postgres:13
    restart: always
    environment:
      - POSTGRES_DB=app
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=supersecretpassword
    container_name: mathew_db
    ports:
      - "5432:5432"

  mathew_api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: mathew_api
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    env_file: .env
    depends_on:
      - mathew_db